### ISSUE TITLE
Add support for pano id

### ISSUE THREAD

**Issue by davidpaulrosser** [mattdesl/google-panorama-equirectangular#5]
Hey,

First of all thanks for this lib, I'm finding it very useful at the moment! Could you add support for panoId's too? Currently it just uses lat / lng for the location.

I'm trying to download a panorama from a google photo sphere but it needs a pano id instead of lat / lng.

Thanks,

David.

**Comment by mattdesl** [comment]
Hmm, the API already expects a `panoId` as the first argument. :smile: In order to go from `[ lat, lon ]` to `panoId` you can use [google-panorama-by-location](https://www.npmjs.com/package/google-panorama-by-location). Or to get tile data from a `panoId` you can use [google-panorama-by-id](https://www.npmjs.com/package/google-panorama-by-id). The `tile` data is recommended for best results.

Whereas this module doesn't actually hit the Google client API at all.
